# Deploy yolo apps

- hosts: local
  gather_facts: False

  tasks:
    - name: Welcome message
      debug: msg="==== Starting Deployment of {{ app.name }} ===="

    - name: Create OpenShift objects
      k8s:
        definition: "{{ lookup('template', item) | from_yaml }}"
        state: present
      with_items: "{{ openshift_templates }}"
