all:
  hosts:
    local:
      ansible_host: 127.0.0.1
      ansible_connection: local
      # Use python from our virtualenv with all dependencies installed instead
      # of the global system-wide python distribution
      ansible_python_interpreter: "/usr/bin/env python"
